// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIPracticeCheckProject.Models;

namespace WebAPIPracticeCheckProject.Migrations
{
    [DbContext(typeof(MenuItemOperation))]
    [Migration("20210325113151_WebAPIPracticeCheckProject.Models.MenuItemOperation-Context-Adding_User_Cart")]
    partial class WebAPIPracticeCheckProjectModelsMenuItemOperationContextAdding_User_Cart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIPracticeCheckProject.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("menuItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("menuItemId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("WebAPIPracticeCheckProject.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfLaunch")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isFreeDelivery")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DateOfLaunch = new DateTime(2021, 1, 20, 0, 3, 0, 0, DateTimeKind.Unspecified),
                            Name = "Poori",
                            Price = 20.0,
                            isActive = true,
                            isFreeDelivery = true
                        });
                });

            modelBuilder.Entity("WebAPIPracticeCheckProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPIPracticeCheckProject.Models.Cart", b =>
                {
                    b.HasOne("WebAPIPracticeCheckProject.Models.MenuItem", "menuItem")
                        .WithMany()
                        .HasForeignKey("menuItemId");

                    b.Navigation("menuItem");
                });
#pragma warning restore 612, 618
        }
    }
}
